# We generally allow wider code lines, but for auto formatting this
# is quite a good rule to produce readable code.
# In ESLint we allow for code being 110 character long, comments 140 characters.
# With auto formatting in place and the current heuristics of prettier it works
# better with a default of 80 characters per line though.
printWidth: 80

# Use two spaces for tabs
tabWidth: 2

# Unify with convention used in JSX, HTML and CSS to use double quotes
singleQuote: false

# Don't use semicolons where they are not required
semi: false

# Don't do stupid trailing commas reducing noise ratio.
trailingComma: none

# More space is better for readability
bracketSpacing: true

# Put the > of a multi-line JSX element at the end of the last line
jsxBracketSameLine: false

# Put parens of around arguments of arrow functions
arrowParens: always
